require 'botfly/responder/common_responder_methods'
require 'botfly/responder/responder'
require 'botfly/responder/message_responder'
require 'botfly/responder/muc_responder'
require 'botfly/responder/subscription_request_responder'